### ISSUE TITLE
Feature request: Please add `indexed_iter()` to traverse the grid with row/col indexes

### ISSUE THREAD

**Issue by jerry73204** [becheran/grid#11]
Mentioned as the title, I'm glad if we can have a `indexed_iter()`, and extension to `iter()` that adds row/col index to each item. That's a great convenience to avoid writing enumerated index by myself.

**Comment by becheran** [comment]
@jerry73204 sounds like a good idea. Though, I won't find the time in the near future to implement it.

If anybody opens a PR on this, I am more than happy to merge it.
