### ISSUE TITLE
Grid::new(usize, usize) panics undocumented

### ISSUE THREAD

**Issue by sadneo** [becheran/grid#17]
This doesn't work
```rs
use grid::Grid;
fn main() {
    let grid : Grid<u8> = Grid::new(usize::MAX, usize::MAX);
}
```
while this does
```rs
use grid::Grid;
  2 fn main() {
  3     let grid : Grid<u8> = Grid::new(u8::MAX, u8::MAX);
  4 }
```
Not really sure how the type annotations would look like, but you should probably update the documentation to say that grid lengths can only be sqrt(usize::MAX)

**Comment by becheran** [comment]
True. It is not possible to have a grid with cols * rows > usize. I will add a note in the docs. Thx

**Comment by becheran** [comment]
Updated docs in `0.8.0`
