### ISSUE TITLE
`Grid::insert_{row, col}()` can create invalid states after panicking

### ISSUE THREAD

**Issue by LegionMammal978** [becheran/grid#19]
The `Grid` type has the effective safety invariants that `rows.checked_mul(cols) == Some(data.len())` and that `rows == 0` if and only if `cols == 0`. In some panicking paths, `Grid::insert_row()` can violate these invariants:

- `grid.insert_row(i, row)` in release mode, where `row.len() == grid.cols` and `grid.rows == usize::MAX`. This sets `grid.rows` to 0, making the other methods' results inconsistent with one another. This is only possible when `size_of::<T>() == 0`, and I'm not sure if it can cause any UB by itself.
- `grid.insert_row(i, row)`, where `i <= grid.rows`, `row.len() == grid.cols`, `grid.rows < usize::MAX`, and `grid.rows * grid.cols > usize::MAX - grid.cols`: This increments `grid.rows` without pushing the new row, allowing invalid `get_unchecked()` calls. Since this is only possible when `size_of::<T>() == 0`, it causes library UB but not language UB with the current standard library.
- `grid.insert_row(i, row)`, where `i <= grid.rows`, `row.len() == grid.cols`, `size_of::<T>() > 0`, and `(grid.rows + 1) * grid.cols * size_of::<T>() > isize::MAX as usize`. This increments `grid.rows` without pushing the new row, which can cause UB on 32-bit targets:
  ```rust
  /*
  [dependencies]
  grid = "=0.8.1"
  
  cargo run --target i686-unknown-linux-gnu
  */
  
  use grid::Grid;
  use std::panic::{self, AssertUnwindSafe};
  
  fn main() {
      let catch = |f| panic::catch_unwind(AssertUnwindSafe(f)).unwrap_err();
      // 1076 * 1994889 == isize::MAX as usize - 983083
      // 1077 * 1994889 == isize::MAX as usize + 1011806
      let mut grid = Grid::init(1076, 1994889, 0u8);
      catch(|| grid.insert_row(1076, vec![0; 1994889]));
      println!("{}", grid.get(1076, 1994888).unwrap()); // segfault
  }
  ```

**Comment by becheran** [comment]
Interesting. Thanks! I guess the solution to this is to panic earlier so the UB is not possible.

**Comment by LegionMammal978** [comment]
Also, it appears that `insert_row()` cannot be used to add a row to an empty grid, which might be useful to support.

**Comment by becheran** [comment]
Fixed with by updating index after altering vector and also added possibility to insert into empty grids
