### ISSUE TITLE
requesing feature: `iter_rows()`, and `iter_cols()`

### ISSUE THREAD

**Issue by IzaakC** [becheran/grid#23]
I'd like to be able to do the following:

```
grid.iter_rows(|row| row.iter_row().sum()).collect::<Vec<_>>()
```

same for cols. This could be a great feature when trying to apply functions row or column wise.

I'm new to Rust, but if you have the  patience I'd be interested in creating a pr myself. 

:)

**Comment by becheran** [comment]
Thx for your interest. I am very patient. PRs to improve the crate are always welcome 👍
