### ISSUE TITLE
Add ability to get slice of row.

### ISSUE THREAD

**Issue by fritzrehde** [becheran/grid#38]
I would like to be able to get an entire row as a slice. Since the internal vector saves the rows continuously (at least for one of the allocation options, right?), it would be useful to be able to get such a slice, instead of an iterator with `.iter_rows`. In my use-case, this iterator wouldn't work, because I need to `.rev()` the rows, and that only works with a slice as far as I'm aware.

**Comment by fritzrehde** [comment]
Actually, a (probably) simpler implementation that would also solve my problem: `grid.iter_rows()` should return a `DoubleEndedIterator`, then I can call `grid.iter_rows().rev()`, which I need.

**Comment by henryiii** [comment]
Guessing this is for Day 14 of AoC? :) If that's the case, you probably need `iter_rows_mut`/`iter_cols_mut`, as you probably want to mutate the contents. I did this by creating the index/col iterator as a usize then using `iter_row_mut`/`tier_col_mut`. Also, you need to reverse the row or column, not the collection of rows and columns, and that is supported already. See https://github.com/henryiii/aoc2023/blob/main/src/bin/14.rs for my solution.

`iter_rows_mut`/`iter_cols_mut` would have made it a bit more elegant.
