### ISSUE TITLE
Implement IntoIterator trait

### ISSUE THREAD

**Issue by vil-mo** [becheran/grid#49]

**Comment by becheran** [comment]
@vil-mo could you please provide a descrpiption of what you want to achieve?

**Comment by henryiii** [comment]
I've silenced this warning in #58, but I think this would be to allow `for val in grid` vs. the current requirement of `for val in grid.iter()`. Leaving it off would enforce that you choose a iter method. But I think it's very common that iteration maps to `.iter()`.
